### ISSUE TITLE
Dark Mode icon brings the page back to its top

### ISSUE THREAD

**Issue by saglaniharsh** [ashawe/PersonalWebsite#9]

**Comment by eemike07** [comment]
I wasn't able to replicate - Toggling Dark Mode icon doesn't move the page.
Specs:
Ubuntu 20
Latest Firefox

**Comment by saglaniharsh** [comment]
Try it on "MyStory" Page

**Comment by eemike07** [comment]
Ah, that did it!  Ok, I'll investigate :)  Please assign to me.

**Comment by eemike07** [comment]
Hello, could you please link this to https://github.com/ashawe/PersonalWebsite/pull/10 and close ticket as resolved.
Also add label: `hacktoberfest-accepted`
:)  Thank you!  Really appreciate it!

**Comment by saglaniharsh** [comment]
@eemike07 I've already added hacktoberfest-accepted in the pr
